# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone("https://github.com/tawheeler/Vec.jl.git"); Pkg.clone(pwd()); Pkg.test("NGSIM"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("NGSIM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
